sonar.projectKey=LeangOC_OC2P7
sonar.organization=leangoc

sonar.sources=back/src/main
sonar.tests=back/src/test

sonar.java.binaries=back/build/classes

sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml